### PR TITLE
Created Blockchain Smart Contracts

### LINKED ISSUE #16: [Feature Request]: Creation of Blockchain Smart Contracts
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature Description

Using Foundry, a solidity framework, to create, test and deploy a smart contract on blockchain that can used to enhance the security of the project.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by ShivRaiGithub**
Fixes #16 
Added Simple Blockchain Smart contracts as discussed. Implemented the Deploy scripting and Testing with an updated Readme about the contracts and processes.

### CODE REVIEW

**Comment by vigneshs-dev** [comment]
> Fixes #16 Added Simple Blockchain Smart contracts as discussed. Implemented the Deploy scripting and Testing with an updated Readme about the contracts and processes.

Hi @ShivRaiGithub ,
Now only I also updated the main branch with enhanced Quantum Entanglement logic. Can you please check it once and convey your points please? You can use the link to view it online.

Because I am new to the blockchain topic. So only I am asking.

**Comment by ShivRaiGithub** [comment]
Hi @vigneshs-dev  In my opinion it looks better than before from the perspective of a user since it provides a clear path of signing up, logging in, voting and then getting the result. The part, for now, where I would suggest having the blockchain integrated, like I told, would be the voting part only. Since I already knew you had 4 candidates, I made sure the blockchain contract started with 4 candidates after deploying. Here is what I suggest for now: You can try experimenting with the code of this PR to get kind of familiar with the process. You will later need to download a wallet extension ( like metamask ) in order to execute the actions required for blockchain voting. I know it might be too much for you as beginner. You can connect with me on discord if you feel any issue. My id is ._.guesswho

**Comment by ShivRaiGithub** [comment]
I made sure the Readme in Foundry_contracts folder is as helpful as possible along with the comments in Voting.sol.  You can also try copying the code of Voting.sol to https://remix.ethereum.org/ and experimenting there before we move to using a library to integrate the frontend and backend.

**Comment by vigneshs-dev** [comment]
> I made sure the Readme in Foundry_contracts folder is as helpful as possible along with the comments in Voting.sol. You can also try copying the code of Voting.sol to https://remix.ethereum.org/ and experimenting there before we move to using a library to integrate the frontend and backend.

Sure @ShivRaiGithub . I will go through the Blockchain part and try to get an idea on that. Within one or two days, I will make myself clear on that. Then I will merge your PR with my main branch. If I experience any difficulties, I will contact you in Discord. Thankyou for your great work. That's really a lot of work on your side.

**Comment by ShivRaiGithub** [comment]
@vigneshs-dev Sent a friend request to your discord id.
Also the error you are seeing is because you are not in the Foundry_contracts folder. Kind of like how you need to be in the react folder when executing `npm run start`

**Comment by vigneshs-dev** [comment]
Hi @ShivRaiGithub ,
I am trying to merge your PR to main branch. I will continue studying on Blockchains and your logic. But till then, I am not Okay in making your PR to wait. Can you please once again update your code with latest changes and tell me. Then I will merge it with main branch. 

If it's not conflicting with implementation, it won't be a problem for me to merge it.

**Comment by ShivRaiGithub** [comment]
Hi @vigneshs-dev 
For the merge, since I have only created a new folder, I dont think it should pose a problem.

Here it also says that there are no conflicts with login_voting_result_db branch. You can merge this PR to that branch. Later when you complete your work on that branch, you can merge the whole branch to the main.
image

**Comment by vigneshs-dev** [comment]
I can't merge it with another branch. Now, I will merge it with main branch. There won't be any conflicts in the project deployment.

**Comment by vigneshs-dev** [comment]
Hi @ShivRaiGithub ,
Your PR Request is merged with my login_voting_result_db branch Successfully. Thankyou for your contribution.

**Pull request merged**
