### PR TITLE
Login and signup pages are workin

### PR DESCRIPTION
**Pull request by Priyanshu-su30**
Done with the Login and signup 
After signup the the page redirects to login and after logging in it takes you to the voting page
Fixes : #7 
Screenshot (233)
Screenshot (234)
Screenshot (235)

### CODE REVIEW

**Comment by vigneshs-dev** [comment]
Hi @Priyanshu-su30 ,
It looks great. I will merge it immediately. Thankyou for your contribution. You have worked so many hours on this issue. Special thanks for that effort. Keep contributing.

**Comment by vigneshs-dev** [comment]
Hi @Priyanshu-su30 ,
Your work merged with the main branch perfectly. You can see that live in the website. I want you to ask you that if you have time, you can work on this follow up work. Like the login and signup page, apply your CSS styles to both the voting and results page. Is you are ok with it, please notify me. I will assign this to you. Once again thanks for this wonderful frontend work.

**Comment by Priyanshu-su30** [comment]
> Hi @Priyanshu-su30 , It looks great. I will merge it immediately. Thankyou for your contribution. You have worked so many hours on this issue. Special thanks for that effort. Keep contributing.

Thank you @vigneshs-dev for giving me this opportunity I also enjoyed the work and even learned new things.

**Comment by Priyanshu-su30** [comment]
> Hi @Priyanshu-su30 , Your work merged with the main branch perfectly. You can see that live in the website. I want you to ask you that if you have time, you can work on this follow up work. Like the login and signup page, apply your CSS styles to both the voting and results page. Is you are ok with it, please notify me. I will assign this to you. Once again thanks for this wonderful frontend work.

@vigneshs-dev I would love to work with you.

**Pull request merged**
