### PR TITLE
Updates:

### PR DESCRIPTION
**Pull request by AlexanderSanin**
1 Simplified Code: Removed redundant comments and streamlined the code for better readability.
2 Dictionary Comprehension: Used dictionary comprehension to create vote_counts more concisely.
3 Figure Creation: Used fig, ax = plt.subplots() for more flexible plotting.
4 Docstrings: Simplified docstrings for clarity.

### CODE REVIEW

**Comment by AlexanderSanin** [comment]
@vigneshs-dev please review

**Comment by vigneshs-dev** [comment]
> @vigneshs-dev please review

Hi @AlexanderSanin , 
On which issue you are working. I don't see any major changes in your code. I am also updating my backend logic. So, I think it won't be necessary for now. Please create issue and ask the owner before start working in any project. Otherwise I don't know who are all working and we don't know whether that work is needed or not.

**Comment by AlexanderSanin** [comment]
> > @vigneshs-dev please review
> 
> Hi @AlexanderSanin , On which issue you are working. I don't see any major changes in your code. I am also updating my backend logic. So, I think it won't be necessary for now. Please create issue and ask the owner before start working in any project. Otherwise I don't know who are all working and we don't know whether that work is needed or not.

@vigneshs-dev 
got it, actully I'm new to the open source, so I wasn't aware that PRs should be tighed to issues. The purpose of the PR was code optimization, in case if it's not meaningful please close the PR

**Comment by vigneshs-dev** [comment]
Hi @AlexanderSanin ,
It is not compulsory to create a issue before working. But, it's a good practise. I updated the logic with new code. As you asked I am closing this PR. You can work on other issues if you want. Thankyou for your contribution.

**Pull request closed without merging**
