### PR TITLE
Add login and signup page

### PR DESCRIPTION
**Pull request by Priyanshu-su30**
Made a new navbar and add name of the project Q-Vote to the left of it and signup and login button on the right most 
Solves issue #7 
Screenshot (217)
Screenshot (218)
Screenshot (219)

### CODE REVIEW

**Comment by vigneshs-dev** [comment]
Hi @Priyanshu-su30 ,
I am working on main Quantum Entanglement logic. So I have to update the backend. Once I complete that, I will integrate your login and sign up page. Thankyou for your contribution .

**Comment by Priyanshu-su30** [comment]
@vigneshs-dev Thank you

**Comment by vigneshs-dev** [comment]
> @vigneshs-dev Thank you

Hi @Priyanshu-su30 ,
I have updated the Quantum logic with enhancement. It now has Register page, Login page, Everything. Can you please update this code with your login and register css files, so that I can merge it with the main branch?

**Comment by Priyanshu-su30** [comment]
@vigneshs-dev sure I'll do it

**Comment by vigneshs-dev** [comment]
Hi @Priyanshu-su30 ,
Have you completed the work?

**Comment by Priyanshu-su30** [comment]
> Hi @Priyanshu-su30 , Have you completed the work?

Yes @vigneshs-dev the work is done

**Comment by vigneshs-dev** [comment]
Hi @Priyanshu-su30 ,
I tried your code locally in my system. I think there are problems in the code. Have you checked your code and try to SignUp and Login?

**Comment by Priyanshu-su30** [comment]
@vigneshs-dev Wait let me check. does this branch login_voting_result_db has the update one or the main branch?

**Comment by vigneshs-dev** [comment]
> @vigneshs-dev Wait let me check. does this branch login_voting_result_db has the update one or the main branch?

I updated the main branch code with login_voting_result_branch. You can upstream from the main branch. Merge your branch with main branch and then upstream from my Repo main branch. Because I want to deploy your sign up and login in render app. To make that I have to merge your code with my main branch only.

**Comment by Priyanshu-su30** [comment]
> Hi @Priyanshu-su30 , I tried your code locally in my system. I think there are problems in the code. Have you checked your code and try to SignUp and Login?

the signup and login are not working and I dont have idea of python

Screenshot (227)

**Comment by Priyanshu-su30** [comment]
Why don't you just delete my code from your's and update your db and then I'll add login and signup page

**Comment by vigneshs-dev** [comment]
You can just delete this PR and upstream from my original repo to your forked repository. Then you can work on improving login and sign in page. Even after following these steps, if you face any problem, please contact me in Discord. 
My Discord ID : vigneshs_dev

**Comment by Priyanshu-su30** [comment]
Closing this as another PR #35  is created with updates and bug fix

**Pull request closed without merging**
