### PR TITLE
Update UI of the Voting and Results page

### LINKED ISSUE #36: [Feature Request]: Update Voting and Results page with CSS styles.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

You have to update the Voting and Results page as same as of Login and Sign up page CSS styles.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by Priyanshu-su30**
The UI of the voting page and the results page is done as per the login/signup page
FIXES: #36
This is the preview for voting page
Screenshot (242)
This is the preview for results page
image

### CODE REVIEW

**Comment by Priyanshu-su30** [comment]
@vigneshs-dev the logout button is not working can you please check

**Comment by Priyanshu-su30** [comment]
Hey @vigneshs-dev , You haven't merged it yet??

**Comment by vigneshs-dev** [comment]
You said that the logout button is not working. So I have to check that. I don't have enough knowledge on Frontend part. So only it's taking time. If you are able to solve that part, it will be great na.

**Comment by Priyanshu-su30** [comment]
Okk I'll also try it.

**Review by Priyanshu-su30 — COMMENTED** [review]
Fix the logout button in both results and vote page

**Comment by Priyanshu-su30** [comment]
Hey @vigneshs-dev, Everything is fix take a look

**Comment by vigneshs-dev** [comment]
> Hey @vigneshs-dev, Everything is fix take a look

 I have some other work. I don't have time to check your code @Priyanshu-su30 . I have confident on you. I will merge it with main code. Thankyou for your contribution. Really means a lot.

**Comment by vigneshs-dev** [comment]
Thankyou so much @Priyanshu-su30 . Your code works fine. The service is live.

**Comment by Priyanshu-su30** [comment]
Thank you @vigneshs-dev that means a lot. If you got any web dev project just remember me. Thanks a lot again I enjoyed contributing to this project and even learned a lot.

**Pull request merged**
